<a href="https://colab.research.google.com/github/AMRISMA/DataScience/blob/master/NN_with_ScikitLearn_Data_Privacy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Implementing Neural Network with Scikit-Learn

In [17]:
import pandas as pd

df = pd.read_csv('diabetes.csv')

In [18]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,target
0,2.0,138.0,62.0,35.0,0.0,33.6,0.13,47.0,1.0
1,0.0,84.0,82.0,31.0,125.0,38.2,0.23,23.0,0.0
2,0.0,145.0,0.0,0.0,0.0,44.2,0.63,31.0,1.0
3,0.0,135.0,68.0,42.0,250.0,42.3,0.37,24.0,1.0
4,1.0,139.0,62.0,41.0,480.0,40.7,0.54,21.0,0.0

In [19]:
# Assign data from first four columns to X variable
X = df.iloc[:, 0:8]
X.head

<bound method NDFrame.head of       Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0             2.0    138.0           62.0           35.0      0.0  33.6
1             0.0     84.0           82.0           31.0    125.0  38.2
2             0.0    145.0            0.0            0.0      0.0  44.2
3             0.0    135.0           68.0           42.0    250.0  42.3
4             1.0    139.0           62.0           41.0    480.0  40.7
...           ...      ...            ...            ...      ...   ...
1995          2.0     75.0           64.0           24.0     55.0  29.7
1996          8.0    179.0           72.0           42.0    130.0  32.7
1997          6.0     85.0           78.0            0.0      0.0  31.2
1998          0.0    129.0          110.0           46.0    130.0  67.1
1999          2.0     81.0           72.0           15.0     76.0  30.1

      DiabetesPedigreeFunction   Age
0                         0.13  47.0
1                         0.23  23.0
2                         0.63  31.0
3                         0.37  24.0
4                         0.54  21.0
...                        ...   ...
1995                      0.37  33.0
1996                      0.72  36.0
1997                      0.38  42.0
1998                      0.32  26.0
1999                      0.55  25.0

[2000 rows x 8 columns]>

In [20]:
# Assign data from first fifth columns to y variable
Y = df.target
Y.head

<bound method NDFrame.head of 0       1.0
1       0.0
2       1.0
3       1.0
4       0.0
       ...
1995    0.0
1996    1.0
1997    0.0
1998    1.0
1999    0.0
Name: target, Length: 2000, dtype: float64>

You can see that the values in the y series are categorical. However, neural networks work better with numerical data. Our next task is to convert these categorical values to numerical values. But first let's see how many unique values we have in our y series. Execute the following script:

We have three unique classes 'Iris-setosa', 'Iris-versicolor' and 'Iris-virginica'. Let's convert these categorical values to numerical values. To do so we will use Scikit-Learn's LabelEncoder class.

Execute the following script:

Now if you again check unique values in the y series, you will see following results:

In [26]:
# Apply generalization by transforming to binary data
X['Age'] = X['Age'].apply(lambda x:">=40"if x>=40 else"<40" )

# See results
X.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,2.0,138.0,62.0,35.0,0.0,33.6,0.13,>=40
1,0.0,84.0,82.0,31.0,125.0,38.2,0.23,<40
2,0.0,145.0,0.0,0.0,0.0,44.2,0.63,<40
3,0.0,135.0,68.0,42.0,250.0,42.3,0.37,<40
4,1.0,139.0,62.0,41.0,480.0,40.7,0.54,<40

In [41]:
import numpy as np 
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(dtype=np.int, sparse = False, drop='first')
Age_encoded = ohe.fit_transform(X[['Age']])
df2 = pd.DataFrame(Age_encoded, columns = ohe.get_feature_names())
X = pd.concat((X, df2), axis = 1)
X

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,x0_>=40
0,2.0,138.0,62.0,35.0,0.0,33.6,0.13,>=40,1
1,0.0,84.0,82.0,31.0,125.0,38.2,0.23,<40,0
2,0.0,145.0,0.0,0.0,0.0,44.2,0.63,<40,0
3,0.0,135.0,68.0,42.0,250.0,42.3,0.37,<40,0
4,1.0,139.0,62.0,41.0,480.0,40.7,0.54,<40,0
...,...,...,...,...,...,...,...,...,...
1995,2.0,75.0,64.0,24.0,55.0,29.7,0.37,<40,0
1996,8.0,179.0,72.0,42.0,130.0,32.7,0.72,<40,0
1997,6.0,85.0,78.0,0.0,0.0,31.2,0.38,>=40,1
1998,0.0,129.0,110.0,46.0,130.0,67.1,0.32,<40,0
1999,2.0,81.0,72.0,15.0,76.0,30.1,0.55,<40,0

In [46]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,x0_>=40
0,2.0,138.0,62.0,35.0,0.0,33.6,0.13,1
1,0.0,84.0,82.0,31.0,125.0,38.2,0.23,0
2,0.0,145.0,0.0,0.0,0.0,44.2,0.63,0
3,0.0,135.0,68.0,42.0,250.0,42.3,0.37,0
4,1.0,139.0,62.0,41.0,480.0,40.7,0.54,0
...,...,...,...,...,...,...,...,...
1995,2.0,75.0,64.0,24.0,55.0,29.7,0.37,0
1996,8.0,179.0,72.0,42.0,130.0,32.7,0.72,0
1997,6.0,85.0,78.0,0.0,0.0,31.2,0.38,1
1998,0.0,129.0,110.0,46.0,130.0,67.1,0.32,0
1999,2.0,81.0,72.0,15.0,76.0,30.1,0.55,0

# Train Test Split
To avoid over-fitting, we will divide our dataset into training and test splits. The training data will be used to train the neural network and the test data will be used to evaluate the performance of the neural network. This helps with the problem of over-fitting because we're evaluating our neural network on data that it has not seen (i.e. been trained on) before.

To create training and test splits, execute the following script:

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.20)

# Feature Scaling
Before making actual predictions, it is always a good practice to scale the features so that all of them can be uniformly evaluated. Feature scaling is performed only on the training data and not on test data. This is because in real world, data is not scaled and the ultimate purpose of the neural network is to make predictions on real world data. Therefore, we try to keep our test data as real as possible.

In [48]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

# Training and Predictions
And now it's finally time to do what you have been waiting for, train a neural network that can actually make predictions. To do this, execute the following script:

In [49]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)
mlp.fit(X_train, Y_train.values.ravel())

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:696: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  ConvergenceWarning,

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

With Scikit-Learn, you can create neural network with these three lines of code, which all handles much of the leg work for you. Let's see what is happening in the above script. The first step is to import the MLPClassifier class from the sklearn.neural_network library. In the second line, this class is initialized with two parameters.

The first parameter, hidden_layer_sizes, is used to set the size of the hidden layers. In our script we will create three layers of 10 nodes each. There is no standard formula for choosing the number of layers and nodes for a neural network and it varies quite a bit depending on the problem at hand. The best way is to try different combinations and see what works best.

The second parameter to MLPClassifier specifies the number of iterations, or the epochs, that you want your neural network to execute. Remember, one epoch is a combination of one cycle of feed-forward and back propagation phase.

By default the 'relu' activation function is used with 'adam' cost optimizer. However, you can change these functions using the activation and solver parameters, respectively.

In the third line the fit function is used to train the algorithm on our training data i.e. X_train and y_train.

# Making Predictions
The final step is to make predictions on our test data. To do so, execute the following script:

In [50]:
predictions = mlp.predict(X_test)

# Evaluating the Algorithm

We created our algorithm and we made some predictions on the test dataset. Now is the time to evaluate how well our algorithm performs. To evaluate an algorithm, the most commonly used metrics are a confusion matrix, precision, recall, and f1 score. The confusion_matrix and classification_report methods of the sklearn.metrics library can help us find these scores. The following script generates evaluation report for our algorithm

In [51]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(Y_test,predictions))
print(classification_report(Y_test,predictions))

[[230  24]
 [ 34 112]]
              precision    recall  f1-score   support

         0.0       0.87      0.91      0.89       254
         1.0       0.82      0.77      0.79       146

    accuracy                           0.85       400
   macro avg       0.85      0.84      0.84       400
weighted avg       0.85      0.85      0.85       400